# Generated by Django 4.1 on 2024-03-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="subcomment",
            name="post",
        ),
        migrations.AlterField(
            model_name="subcomment",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_comments",
                to="app.comment",
            ),
        ),
    ]
