# Generated by Django 4.1 on 2024-03-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_comment_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_at"]},
        ),
    ]
