# Generated by Django 4.1 on 2024-03-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_comment_parent_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
