# Generated by Django 5.0.2 on 2024-03-05 18:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                default=1, upload_to=app.models.post_photo_file_path
            ),
            preserve_default=False,
        ),
    ]
