# Generated by Django 5.0.2 on 2024-03-05 20:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.post_photo_file_path
            ),
        ),
    ]
